name: Staging Deployment

on:
  push:
    branches: [main]

jobs:
  build-staging:
    name: Build Staging
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Push to GitHub Packages
        id: "build-push-docker"
        uses: docker/build-push-action@v2
        env:
          DIGEST: steps.run_tests.outputs.digest
          SHA: steps.sha.outputs.sha_short
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ghcr.io/farizap/docker-hello-world:latest,ghcr.io/farizap/docker-hello-world:${{steps.sha.outputs.sha_short}}